openapi: 3.0.3
info:
  title: Test API
  description: Test API
  version: 0.0.1
servers:
- url: http://localhost:8080
paths:
  /users:
    get:
      operationId: listUsers
      parameters:
      - name: id
        in: query
        schema:
          type: array
          items:
            type: integer
            format: int64
      - name: filter
        in: query
        style: form
        schema:
          $ref: '#/components/schemas/UserFilter'
      - name: q
        in: query
        schema:
          type: string
      - name: sort-order
        in: query
        style: form
        schema:
          $ref: '#/components/schemas/UserSortOrder'
      - name: start-end
        in: query
        style: form
        schema:
          $ref: '#/components/schemas/SampleStartEnd'
      responses:
        "200":
          description: OK
          headers:
            X-Total-Count:
              schema:
                type: string
              example: "X-Total-Count: 319"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      operationId: readUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      operationId: updateUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /companies:
    get:
      operationId: listCompanies
      parameters:
      - name: id
        in: query
        schema:
          type: array
          items:
            type: integer
            format: int64
      - name: filter
        in: query
        style: form
        schema:
          $ref: '#/components/schemas/CompanyFilter'
      - name: q
        in: query
        schema:
          type: string
      - name: sort-order
        in: query
        style: form
        schema:
          $ref: '#/components/schemas/CompanySortOrder'
      - name: start-end
        in: query
        style: form
        schema:
          $ref: '#/components/schemas/SampleStartEnd'
      responses:
        "200":
          description: OK
          headers:
            X-Total-Count:
              schema:
                type: string
              example: "X-Total-Count: 319"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
    post:
      operationId: createCompany
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyCreate'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
  /companies/{id}:
    get:
      operationId: readCompany
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
    put:
      operationId: updateCompany
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyUpdate'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
    delete:
      operationId: deleteCompany
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /employees:
    get:
      operationId: listEmployees
      parameters:
      - name: id
        in: query
        schema:
          type: array
          items:
            type: integer
            format: int64
      - name: filter
        in: query
        style: form
        schema:
          $ref: '#/components/schemas/EmployeeFilter'
      - name: q
        in: query
        schema:
          type: string
      - name: sort-order
        in: query
        style: form
        schema:
          $ref: '#/components/schemas/EmployeeSortOrder'
      - name: start-end
        in: query
        style: form
        schema:
          $ref: '#/components/schemas/SampleStartEnd'
      responses:
        "200":
          description: OK
          headers:
            X-Total-Count:
              schema:
                type: string
              example: "X-Total-Count: 319"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      operationId: createEmployee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeCreate'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
  /employees/{id}:
    get:
      operationId: readEmployee
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
    put:
      operationId: updateEmployee
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeUpdate'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
    delete:
      operationId: deleteEmployee
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
components:
  schemas:
    UserFilter:
      title: UserFilter
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        displayName:
          type: string
    User:
      title: User
      required:
      - id
      - email
      - displayName
      - currentEmployeeId
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        displayName:
          type: string
        currentEmployeeId:
          type: integer
          format: int64
    UserSortOrder:
      title: UserSortOrder
      type: object
      properties:
        _sort:
          $ref: '#/components/schemas/UserSortPropertyId'
        _order:
          $ref: '#/components/schemas/SampleOrderDirection'
      x-implements: "org.wintersleep.openapi.crud.core.provider.SortOrder<org.wintersleep.openapi.crud.sample.api.model.UserSortPropertyId,\
        \ org.wintersleep.openapi.crud.sample.api.model.SampleOrderDirection>"
    UserSortPropertyId:
      title: UserSortPropertyId
      enum:
      - id
      - email
      - firstName
      - lastName
      - displayName
    UserCreate:
      title: UserCreate
      required:
      - email
      - displayName
      properties:
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        displayName:
          type: string
    UserUpdate:
      title: UserUpdate
      required:
      - displayName
      properties:
        firstName:
          type: string
        lastName:
          type: string
        displayName:
          type: string
    CompanyFilter:
      title: CompanyFilter
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          $ref: '#/components/schemas/CompanyType'
        vatNumber:
          type: string
          format: vat
        externalId:
          type: string
        verified:
          type: boolean
        lastVerifiedAt:
          type: string
          format: date-time
        lastUnverifiedAt:
          type: string
          format: date-time
    Company:
      title: Company
      required:
      - id
      - name
      - type
      - vatNumber
      - address
      - verified
      - lastVerifiedAt
      - lastUnverifiedAt
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          $ref: '#/components/schemas/CompanyType'
        vatNumber:
          type: string
          format: vat
        externalId:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        url:
          type: string
          format: url
        verified:
          type: boolean
        lastVerifiedAt:
          type: string
          format: date-time
        lastUnverifiedAt:
          type: string
          format: date-time
    CompanySortOrder:
      title: CompanySortOrder
      type: object
      properties:
        _sort:
          $ref: '#/components/schemas/CompanySortPropertyId'
        _order:
          $ref: '#/components/schemas/SampleOrderDirection'
      x-implements: "org.wintersleep.openapi.crud.core.provider.SortOrder<org.wintersleep.openapi.crud.sample.api.model.CompanySortPropertyId,\
        \ org.wintersleep.openapi.crud.sample.api.model.SampleOrderDirection>"
    CompanySortPropertyId:
      title: CompanySortPropertyId
      enum:
      - id
      - name
      - type
      - vatNumber
      - externalId
      - verified
      - lastVerifiedAt
      - lastUnverifiedAt
    CompanyCreate:
      title: CompanyCreate
      required:
      - name
      - type
      - vatNumber
      - address
      - verified
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/CompanyType'
        vatNumber:
          type: string
          format: vat
        externalId:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        url:
          type: string
          format: url
        verified:
          type: boolean
    CompanyUpdate:
      title: CompanyUpdate
      required:
      - name
      - type
      - address
      - verified
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/CompanyType'
        address:
          $ref: '#/components/schemas/Address'
        url:
          type: string
          format: url
        verified:
          type: boolean
    EmployeeFilter:
      title: EmployeeFilter
      properties:
        id:
          type: integer
          format: int64
        active:
          type: boolean
        lastActivatedAt:
          type: string
          format: date-time
        lastDeActivatedAt:
          type: string
          format: date-time
        userId:
          type: integer
          format: int64
        companyId:
          type: integer
          format: int64
    Employee:
      title: Employee
      required:
      - id
      - active
      - lastActivatedAt
      - lastDeActivatedAt
      - userId
      - companyId
      properties:
        id:
          type: integer
          format: int64
        active:
          type: boolean
        lastActivatedAt:
          type: string
          format: date-time
        lastDeActivatedAt:
          type: string
          format: date-time
        userId:
          type: integer
          format: int64
        companyId:
          type: integer
          format: int64
    EmployeeSortOrder:
      title: EmployeeSortOrder
      type: object
      properties:
        _sort:
          $ref: '#/components/schemas/EmployeeSortPropertyId'
        _order:
          $ref: '#/components/schemas/SampleOrderDirection'
      x-implements: "org.wintersleep.openapi.crud.core.provider.SortOrder<org.wintersleep.openapi.crud.sample.api.model.EmployeeSortPropertyId,\
        \ org.wintersleep.openapi.crud.sample.api.model.SampleOrderDirection>"
    EmployeeSortPropertyId:
      title: EmployeeSortPropertyId
      enum:
      - id
      - active
      - lastActivatedAt
      - lastDeActivatedAt
      - userId
      - companyId
    EmployeeCreate:
      title: EmployeeCreate
      required:
      - active
      - userId
      - companyId
      properties:
        active:
          type: boolean
        userId:
          type: integer
          format: int64
        companyId:
          type: integer
          format: int64
    EmployeeUpdate:
      title: EmployeeUpdate
      required:
      - active
      properties:
        active:
          type: boolean
    CompanyType:
      type: string
      enum:
      - supplier
      - customer
    Address:
      title: Address
      required:
      - street
      - streetNumber
      - zipCode
      - city
      - country
      properties:
        street:
          type: string
        streetNumber:
          type: string
        zipCode:
          type: string
        city:
          type: string
        country:
          type: string
          format: CountryCode
    SampleOrderDirection:
      type: string
      enum:
      - ASC
      - DESC
    SampleStartEnd:
      type: object
      properties:
        _start:
          minimum: 0
          type: integer
          format: int64
        _end:
          maximum: 1000
          minimum: 1
          type: integer
          format: int64
      x-implements: org.wintersleep.openapi.crud.core.provider.StartEnd
