#$schema: "https://json-schema.org/draft/2020-12/schema",
$id: https://wintersleep.org/openapi-crud.schema.yml
title: CrudDefinition
type: object
properties:
  enums:
    type: array
    items:
      type: object
      title: EnumDefinition
      javaType: org.wintersleep.openapi.crud.model.internal.EnumDefinition
      properties:
        name:
          type: string
        values:
          type: array
          items:
            type: string
      required:
        - name
        - values
  entities:
    type: array
    items:
      type: object
      title: Entity
      additionalProperties: false
      properties:
        title:
          type: string
        pluralTitle:
          type: string
        path:
          type: string
        parent:
          type: string
        operations:
          type: string
          pattern: l?c?r?u?d?
        audit:
          type: string
          pattern: c?u?d?
        search:
          type: boolean
        properties:
          type: object
          existingJavaType: java.util.Map<String,String>
      required:
        - path
        - title
        - pluralTitle
        - operations
        - properties
