spring:
  application:
    name: Crud Sample
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/crud
    username: crud
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: debug
    org.hibernate: info
    org.springframework.orm: info
